In [28]:
import numpy as np
import pandas as pd
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
df.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [8]:
from sklearn.preprocessing import StandardScaler

columns_to_scale = ['Age', 'EstimatedSalary']
scaler = StandardScaler()
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])
print(df)

          Age  EstimatedSalary  Purchased
0   -1.781797        -1.490046          0
1   -0.253587        -1.460681          0
2   -1.113206        -0.785290          0
3   -1.017692        -0.374182          0
4   -1.781797         0.183751          0
..        ...              ...        ...
395  0.797057        -0.844019          1
396  1.274623        -1.372587          1
397  1.179110        -1.460681          1
398 -0.158074        -1.078938          0
399  1.083596        -0.990844          1

[400 rows x 3 columns]


In [11]:
from sklearn.model_selection import train_test_split
X = df[['Age', 'EstimatedSalary']]
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train

Age  EstimatedSalary
3   -1.017692        -0.374182
18   0.797057        -1.225763
202  0.128465         1.886912
250  0.606031        -0.902749
274  1.847701        -1.284492
..        ...              ...
71  -1.304232        -1.255127
106 -1.113206        -1.020209
270  0.510518         1.857547
348  0.128465         0.213115
102 -0.540127         0.477399

[320 rows x 2 columns]

In [15]:
X_test

Age  EstimatedSalary
209  0.797057        -1.401952
280  2.038728         0.536129
33  -0.922179        -0.755925
210  0.988083         0.771048
93  -0.826666        -1.225763
..        ...              ...
246 -0.253587        -0.579736
227  1.752188         1.857547
369  1.561162        -1.284492
176 -0.253587        -0.667830
289 -0.062561         0.242480

[80 rows x 2 columns]

In [17]:
y_train

3      0
18     1
202    1
250    0
274    1
      ..
71     0
106    0
270    0
348    0
102    0
Name: Purchased, Length: 320, dtype: int64

In [19]:
y_test

209    0
280    1
33     0
210    1
93     0
      ..
246    0
227    1
369    1
176    0
289    1
Name: Purchased, Length: 80, dtype: int64

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [23]:
y_pred

array([ 0.36269954,  0.97356109, -0.00371156,  0.72662375, -0.04583675,
        0.12344117,  0.74760863,  0.18670667,  0.43364401,  0.442411  ,
        0.26374437,  0.59210291, -0.11441833, -0.2966913 ,  0.22914272,
        0.44555105,  0.58349136,  0.58255877,  0.26859416,  0.77860394,
       -0.22873144,  0.17402248,  0.39245141,  0.92282435, -0.33912735,
        0.49454662,  0.50583193,  0.26405523,  1.02790418, -0.33067122,
        0.44303272, -0.12349618,  0.62328509,  0.14427062,  0.568942  ,
        0.30602499,  0.27251136,  0.34031578, -0.11395204, -0.15747611,
        0.46025583, -0.05929809, -0.2251251 ,  0.37976722, -0.18676168,
        0.80633521,  0.0936893 ,  0.18701753,  0.49408033,  0.1452032 ,
        0.0676992 ,  0.7950499 ,  0.29803516,  0.07192727,  0.37821291,
       -0.08420017,  1.05827777,  0.25811743,  0.19970172,  0.20815784,
        0.35769433,  0.22991988,  0.80335059,  0.17809511,  0.05970937,
        0.36397442,  0.54811255,  0.90404693,  0.34047121,  0.41

In [25]:
new_data = [[30, 5000]]
predict_value = model.predict(new_data)
print("predicted value : ", predict_value)

predicted value :  [728.28715845]


C:\Users\donsh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [34]:
from sklearn.preprocessing import MinMaxScaler

data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
print("Original data:")
print(data)

print("\n Scaled data:")
print(scaled_data)

Original data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

 Scaled data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [39]:
data1 = {
    'A':[10,20,30,40,50],
    'B':[1,2,3,4,5],
    'C':[5,10,15,20,25]
}
df = pd.DataFrame(data1)

numerical_cols = ['A', 'B', 'C']
X = df[numerical_cols]

scaler = MinMaxScaler()

X_scaler = scaler.fit_transform(X)

df[numerical_cols] = X_scaler

print("Original data")
print(df)

Original data
      A     B     C
0  0.00  0.00  0.00
1  0.25  0.25  0.25
2  0.50  0.50  0.50
3  0.75  0.75  0.75
4  1.00  1.00  1.00


In [45]:
from sklearn import datasets
diabet = datasets.load_diabetes()

df = pd.DataFrame(data=diabet.data, columns = diabet.feature_names)
numerical_cols = df.columns
X = df[numerical_cols]

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)

df[numerical_cols] = X_scaled

print("Original data:")
print(df.head())

Original data:
        age  sex       bmi        bp        s1        s2        s3        s4  \
0  0.666667  1.0  0.582645  0.549296  0.294118  0.256972  0.207792  0.282087   
1  0.483333  0.0  0.148760  0.352113  0.421569  0.306773  0.623377  0.141044   
2  0.883333  1.0  0.516529  0.436620  0.289216  0.258964  0.246753  0.282087   
3  0.083333  0.0  0.301653  0.309859  0.495098  0.447211  0.233766  0.423131   
4  0.516667  0.0  0.206612  0.549296  0.465686  0.417331  0.389610  0.282087   

         s5        s6  
0  0.562217  0.439394  
1  0.222443  0.166667  
2  0.496584  0.409091  
3  0.572936  0.469697  
4  0.362369  0.333333  
